spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/thinkal01/SpringCloud_Sell
          search-paths: config-repo
          username: thinkal01
          password: git1991726
          # uri: https://gitlab-demo.com/SpringCloud_Sell/config-repo.git
          # username: lly835@163.com #账号密码写真实的快一些，不使用也能访问有点慢
          # password: nKfm9JMUfWEh
          # 搜索目录,配置文件存放在二级目录下时使用
          # search-paths: config
          # basedir: /Users/admin/code/myProjects/java/imooc/SpringCloud_Sell/config/basedir
      # 读取分支
      label: master
