server:
  port: 8089
spring:
  application:
    name: config
  profiles:
    active: gitee

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

# 暴露接口
management:
  endpoints:
    web:
      exposure:
        include: "*"