consistent:
  hash:
    # 需要用一致性hash处理的服务
    service: "{'cli*': 'iPAddr'}"
    # 采用一致性hash处理的最大请求体长度
    maxRequestContentLength: 100000

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.http.server.reactive: INFO
    org.springframework.web.reactive: INFO
    reactor.ipc.netty: INFO
ribbon:
  # 饥饿加载模式
  eager-load:
    enabled: true